description: "Build the static website"
steps:
  - checkout
  - setup_environment:
      install_node: true
      install_tailscale: false
  - run:
      name: Build Static Site
      command: |
        echo "Building static site..."
        npm install
        npm run build
