description: "Build the static website"
executor: cimg/node:18.20.3
steps:
  - checkout
  - run:
      name: Build Static Site
      command: |
        echo "Building static site..."
        npm install
        npm run build
