description: "Setup common environment with Node.js and Tailscale"
parameters:
  install_node:
    type: boolean
    default: true
    description: "Whether to install Node.js"
  install_tailscale:
    type: boolean
    default: true
    description: "Whether to install Tailscale"
steps:
  - run:
      name: Install Node.js
      when: <<parameters.install_node>>
      command: !include src/commands/scripts/install_nodejs.sh
  - run:
      name: Install Tailscale
      when: <<parameters.install_tailscale>>
      command: !include src/commands/scripts/install_tailscale.sh
